name: circus_basket
description: "Base project for the Circus Code Challenge"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  auto_route: ^8.0.3
  auto_route_generator: ^8.0.0
  dev: ^1.0.0
  dio: ^5.4.2+1
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  random_name_generator: ^1.3.0
  rxdart: ^0.27.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.9
  freezed: ^2.5.1
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
